
image: ubuntu:latest

before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    - DEBIAN_FRONTEND=noninteractive apt-get install -y cmake

stages:
    - test

test_job:
    stage: test
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make check

